"""LOG_COLUMNS is append-only: dfit_log.csv files already written must keep reading back."""
from dfit_tool import store

# Append new columns to store.LOG_COLUMNS, then extend FROZEN to match. Never reorder, rename,
# or remove an entry.
FROZEN = [
    'file',
    'test_id',
    'well_name',
    'formation',
    'status',
    'interpreter',
    'review_date',
    'orientation',
    'fluid_type',
    'play',
    'pressure_source',
    'tvd',
    'fluid_density',
    't_start_inj',
    't_shutin',
    'te',
    'Vinj',
    'max_rate',
    'apparent_ISIP',
    'effective_ISIP',
    'closure_scenario',
    'closure_quality',
    'contact_pressure',
    'Shmin_compliance',
    'Shmin_tangent',
    'tangent_Gc',
    'postclosure_scenario',
    'postclosure_trend',
    'pore_pressure',
    'pp_axis',
    'pp_confidence',
    'net_pressure_compliance',
    'net_pressure_tangent',
    'delta_closure',
    'notes',
    'effective_ISIP_tangent',
    'effective_ISIP_variable',
    'Shmin_variable',
    'Shmin_rapid',
    'net_pressure_variable',
    'closure_time_compliance_min',
    'closure_time_tangent_min',
    'closure_time_variable_min',
    'net_pressure_isip_source',
    'near_wellbore_complexity',
    'tail_trim_s',
    'tail_trim_reason',
    'Shmin_liberty',
    'units_note',
    'apparent_ISIP_gradient',
    'Shmin_compliance_gradient',
    'Shmin_variable_gradient',
    'Shmin_tangent_gradient',
    'Shmin_liberty_gradient',
    'Shmin_rapid_gradient',
    'pore_pressure_gradient',
    'Shmin_stiffness',
    'Shmin_stiffness_gradient',
    'stiffness_no_upturn',
    'tail_guard_override',
    'tangent_uninterpretable',
    'apparent_isip_method',
    'postclosure_auto',
    'dropouts_masked',
    'rises_masked',
    'manual_masks',
    'manual_keeps',
    'pce_peak_min',
    'contact_method',
]


def test_log_columns_are_append_only():
    assert list(store.LOG_COLUMNS[:len(FROZEN)]) == FROZEN
